enum Area {
  all('すべて'),
  oceania('大洋州'),
  asia('アジア'),
  africa('アフリカ'),
  europe('欧州'),
  middleEast('中東'),
  northAmerica('北米'),
  latinAmerica('中南米');

  const Area(this.name);

  final String name;

  List<Country> get countries {
    if (this == Area.all) {
      return Country.all;
    }
    return Country.all.where((country) => country.area == name).toList();
  }
}

class Country {
  const Country({
    required this.name,
    required this.englishName,
    required this.capitalCity,
    required this.area,
    required this.imageName,
    required this.language,
    required this.currency,
    required this.nameAnswer,
    required this.capitalAnswer,
  });
  final String area;
  final String name;
  final String englishName;
  final String capitalCity;
  final String imageName;
  final String language;
  final String currency;
  final String nameAnswer;
  final String capitalAnswer;

  static List<Country> all = [
    const Country(
        area: '欧州',
        name: 'アイスランド',
        englishName: 'Iceland',
        capitalCity: 'レイキャビク',
        imageName: 'iceland',
        language: 'アイスランド語',
        currency: 'アイスランド・クローナ',
        nameAnswer: 'あいすらんど',
        capitalAnswer: 'れいきゃびく'),
    const Country(
        area: '欧州',
        name: 'アイルランド',
        englishName: 'Ireland',
        capitalCity: 'ダブリン',
        imageName: 'ireland',
        language: 'アイルランド語（ゲール語）、英語',
        currency: 'ユーロ',
        nameAnswer: 'あいるらんど',
        capitalAnswer: 'だぶりん'),
    const Country(
        area: '欧州',
        name: 'アゼルバイジャン共和国',
        englishName: 'Republic of Azerbaijan',
        capitalCity: 'バクー',
        imageName: 'republic_of_azerbaijan',
        language: 'アゼルバイジャン語（公用語）',
        currency: 'マナト',
        nameAnswer: 'あぜるばいじゃんきょうわこく',
        capitalAnswer: 'ばくー'),
    const Country(
        area: '中東',
        name: 'アフガニスタン・イスラム共和国',
        englishName: 'Islamic Republic of Afghanistan',
        capitalCity: 'カブール',
        imageName: 'islamic_republic_of_afghanistan',
        language: 'ダリー語、パシュトー語（ともに公用語）',
        currency: 'アフガニー',
        nameAnswer: 'あふがにすたん・いすらむきょうわこく',
        capitalAnswer: 'かぶーる'),
    const Country(
        area: '北米',
        name: 'アメリカ合衆国',
        englishName: 'United States of America',
        capitalCity: 'ワシントンD.C.',
        imageName: 'united_states_of_america',
        language: '英語',
        currency: '米ドル',
        nameAnswer: 'あめりかがっしゅうこく',
        capitalAnswer: 'わしんとんでぃーしー'),
    const Country(
        area: '中東',
        name: 'アラブ首長国連邦',
        englishName: 'United Arab Emirates: UAE',
        capitalCity: 'アブダビ',
        imageName: 'united_arab_emirates:_uae',
        language: 'アラビア語',
        currency: 'ディルハム',
        nameAnswer: 'あらぶしゅちょうこくれんぽう',
        capitalAnswer: 'あぶだび'),
    const Country(
        area: 'アフリカ',
        name: 'アルジェリア民主人民共和国',
        englishName: 'People\'s Democratic Republic of Algeria',
        capitalCity: 'アルジェ',
        imageName: 'people_s_democratic_republic_of_algeria',
        language: 'アラビア語、ベルベル語（ともに国語、公用語）、フランス語（国民の間で広く用いられている）',
        currency: 'アルジェリアン・ディナール',
        nameAnswer: 'あるじぇりあみんしゅじんみんきょうわこく',
        capitalAnswer: 'あるじぇ'),
    const Country(
        area: '中南米',
        name: 'アルゼンチン共和国',
        englishName: 'Argentine Republic',
        capitalCity: 'ブエノスアイレス',
        imageName: 'argentine_republic',
        language: 'スペイン語',
        currency: 'ペソ',
        nameAnswer: 'あるぜんちんきょうわこく',
        capitalAnswer: 'ぶえのすあいれす'),
    const Country(
        area: '欧州',
        name: 'アルバニア共和国',
        englishName: 'Republic of Albania',
        capitalCity: 'ティラナ',
        imageName: 'republic_of_albania',
        language: 'アルバニア語',
        currency: 'レク',
        nameAnswer: 'あるばにあきょうわこく',
        capitalAnswer: 'てぃらな'),
    const Country(
        area: '欧州',
        name: 'アルメニア共和国',
        englishName: 'Republic of Armenia',
        capitalCity: 'エレバン',
        imageName: 'republic_of_armenia',
        language: 'アルメニア語（公用語）',
        currency: 'ドラム',
        nameAnswer: 'あるめにあきょうわこく',
        capitalAnswer: 'えればん'),
    const Country(
        area: 'アフリカ',
        name: 'アンゴラ共和国',
        englishName: 'Republic of Angola',
        capitalCity: 'ルアンダ',
        imageName: 'republic_of_angola',
        language: 'ポルトガル語（公用語）、その他ウンブンドゥ語など',
        currency: 'クワンザ',
        nameAnswer: 'あんごらきょうわこく',
        capitalAnswer: 'るあんだ'),
    const Country(
        area: '中南米',
        name: 'アンティグア・バーブーダ',
        englishName: 'Antigua and Barbuda',
        capitalCity: 'セントジョンズ',
        imageName: 'antigua_and_barbuda',
        language: '英語（公用語）、アンティグア・クレオール語',
        currency: '東カリブ・ドル',
        nameAnswer: 'あんてぃぐあ・ばーぶーだ',
        capitalAnswer: 'せんとじょんず'),
    const Country(
        area: '欧州',
        name: 'アンドラ公国',
        englishName: 'Principality of Andorra',
        capitalCity: 'アンドラ・ラ・ベリャ',
        imageName: 'principality_of_andorra',
        language: 'カタルーニャ語（公用語）、スペイン語、ポルトガル語、フランス語',
        currency: 'ユーロ',
        nameAnswer: 'あんどらこうこく',
        capitalAnswer: 'あんどら・ら・べりゃ'),
    const Country(
        area: '中東',
        name: 'イエメン共和国',
        englishName: 'Republic of Yemen',
        capitalCity: 'サヌア',
        imageName: 'republic_of_yemen',
        language: 'アラビア語',
        currency: 'イエメン・リアル',
        nameAnswer: 'いえめんきょうわこく',
        capitalAnswer: 'さぬあ'),
    const Country(
        area: '中東',
        name: 'イスラエル国',
        englishName: 'State of Israel',
        capitalCity: 'テルアビブ',
        imageName: 'state_of_israel',
        language: 'ヘブライ語（公用語）、アラビア語',
        currency: '新シェケル',
        nameAnswer: 'いすらえるこく',
        capitalAnswer: 'てるあびぶ'),
    const Country(
        area: '欧州',
        name: 'イタリア共和国',
        englishName: 'Italian Republic',
        capitalCity: 'ローマ',
        imageName: 'italian_republic',
        language: 'イタリア語',
        currency: 'ユーロ',
        nameAnswer: 'いたりあきょうわこく',
        capitalAnswer: 'ろーま'),
    const Country(
        area: '中東',
        name: 'イラク共和国',
        englishName: 'Republic of Iraq',
        capitalCity: 'バグダッド',
        imageName: 'republic_of_iraq',
        language: 'アラビア語、クルド語（ともに公用語）など',
        currency: 'イラク・ディナール',
        nameAnswer: 'いらくきょうわこく',
        capitalAnswer: 'ばぐだっど'),
    const Country(
        area: '中東',
        name: 'イラン・イスラム共和国',
        englishName: 'Islamic Republic of Iran',
        capitalCity: 'テヘラン',
        imageName: 'islamic_republic_of_iran',
        language: 'ペルシャ語、トルコ語、クルド語など',
        currency: 'リアル',
        nameAnswer: 'いらん・いすらむきょうわこく',
        capitalAnswer: 'てへらん'),
    const Country(
        area: 'アジア',
        name: 'インド共和国',
        englishName: 'Republic of India',
        capitalCity: 'ニューデリー',
        imageName: 'republic_of_india',
        language: 'ヒンディー語(連邦公用語）、憲法公認言語21言語など',
        currency: 'ルピー',
        nameAnswer: 'いんどきょうわこく',
        capitalAnswer: 'にゅーでりー'),
    const Country(
        area: 'アジア',
        name: 'インドネシア共和国',
        englishName: 'Republic of Indonesia',
        capitalCity: 'ジャカルタ',
        imageName: 'republic_of_indonesia',
        language: 'インドネシア語',
        currency: 'ルピア',
        nameAnswer: 'いんどねしあきょうわこく',
        capitalAnswer: 'じゃかるた'),
    const Country(
        area: 'アフリカ',
        name: 'ウガンダ共和国',
        englishName: 'Republic of Uganda',
        capitalCity: 'カンパラ',
        imageName: 'republic_of_uganda',
        language: '英語、スワヒリ語、ルガンダ語',
        currency: 'ウガンダ・シリング',
        nameAnswer: 'うがんだきょうわこく',
        capitalAnswer: 'かんぱら'),
    const Country(
        area: '欧州',
        name: 'ウクライナ',
        englishName: 'Ukraine',
        capitalCity: 'キーウ',
        imageName: 'ukraine',
        language: 'ウクライナ語（国家語）。ロシア語も使われている。',
        currency: 'フリヴニャ',
        nameAnswer: 'うくらいな',
        capitalAnswer: 'きーう'),
    const Country(
        area: '欧州',
        name: 'ウズベキスタン共和国',
        englishName: 'Republic of Uzbekistan',
        capitalCity: 'タシケント',
        imageName: 'republic_of_uzbekistan',
        language: 'ウズベク語（国家語）、ロシア語',
        currency: 'スム',
        nameAnswer: 'うずべきすたんきょうわこく',
        capitalAnswer: 'たしけんと'),
    const Country(
        area: '中南米',
        name: 'ウルグアイ東方共和国',
        englishName: 'Oriental Republic of Uruguay',
        capitalCity: 'モンテビデオ',
        imageName: 'oriental_republic_of_uruguay',
        language: 'スペイン語',
        currency: 'ペソ',
        nameAnswer: 'うるぐあいとうほうきょうわこく',
        capitalAnswer: 'もんてびでお'),
    const Country(
        area: '欧州',
        name: '英国（グレートブリテン及び北アイルランド連合王国）',
        englishName: 'United Kingdom of Great Britain and Northern Ireland',
        capitalCity: 'ロンドン',
        imageName: 'united_kingdom_of_great_britain_and_northern_ireland',
        language: '英語（ウェールズ語、ゲール語等使用地域あり）',
        currency: 'スターリング・ポンド',
        nameAnswer: 'えいこく（ぐれーとぶりてんおよびきたあいるらんどれんごうおうこく）',
        capitalAnswer: 'ろんどん'),
    const Country(
        area: '中南米',
        name: 'エクアドル共和国',
        englishName: 'Republic of Ecuador',
        capitalCity: 'キト',
        imageName: 'republic_of_ecuador',
        language: 'スペイン語（ケチュア語、シュアール語など）',
        currency: '米ドル',
        nameAnswer: 'えくあどるきょうわこく',
        capitalAnswer: 'きと'),
    const Country(
        area: 'アフリカ',
        name: 'エジプト・アラブ共和国',
        englishName: 'Arab Republic of Egypt',
        capitalCity: 'カイロ',
        imageName: 'arab_republic_of_egypt',
        language: 'アラビア語、都市部では英語も通用',
        currency: 'エジプト・ポンド',
        nameAnswer: 'えじぷと・あらぶきょうわこく',
        capitalAnswer: 'かいろ'),
    const Country(
        area: '欧州',
        name: 'エストニア共和国',
        englishName: 'Republic of Estonia',
        capitalCity: 'タリン',
        imageName: 'republic_of_estonia',
        language: 'エストニア語',
        currency: 'ユーロ',
        nameAnswer: 'えすとにあきょうわこく',
        capitalAnswer: 'たりん'),
    const Country(
        area: 'アフリカ',
        name: 'エスワティニ王国',
        englishName: 'Kingdom of Eswatini',
        capitalCity: 'ムババーネ',
        imageName: 'kingdom_of_eswatini',
        language: '英語、スワティ語',
        currency: 'リランゲーニ',
        nameAnswer: 'えすわてぃにおうこく',
        capitalAnswer: 'むばばーね'),
    const Country(
        area: 'アフリカ',
        name: 'エチオピア連邦民主共和国',
        englishName: 'Federal Democratic Republic of Ethiopia',
        capitalCity: 'アディスアベバ',
        imageName: 'federal_democratic_republic_of_ethiopia',
        language: 'アムハラ語、オロモ語、英語など',
        currency: 'ブル',
        nameAnswer: 'えちおぴあれんぽうみんしゅきょうわこく',
        capitalAnswer: 'あでぃすあべば'),
    const Country(
        area: 'アフリカ',
        name: 'エリトリア国',
        englishName: 'State of Eritrea',
        capitalCity: 'アスマラ',
        imageName: 'state_of_eritrea',
        language: 'ティグリニャ語、アラビア語、諸民族語',
        currency: 'ナクファ',
        nameAnswer: 'えりとりあこく',
        capitalAnswer: 'あすまら'),
    const Country(
        area: '中南米',
        name: 'エルサルバドル共和国',
        englishName: 'Republic of El Salvador',
        capitalCity: 'サンサルバドル',
        imageName: 'republic_of_el_salvador',
        language: 'スペイン語',
        currency: '米ドル',
        nameAnswer: 'えるさるばどるきょうわこく',
        capitalAnswer: 'さんさるばどる'),
    const Country(
        area: '大洋州',
        name: 'オーストラリア連邦',
        englishName: 'Commonwealth of Australia',
        capitalCity: 'キャンベラ',
        imageName: 'commonwealth_of_australia',
        language: '英語',
        currency: 'オーストラリア・ドル',
        nameAnswer: 'おーすとらりあれんぽう',
        capitalAnswer: 'きゃんべら'),
    const Country(
        area: '欧州',
        name: 'オーストリア共和国',
        englishName: 'Republic of Austria',
        capitalCity: 'ウィーン',
        imageName: 'republic_of_austria',
        language: 'ドイツ語',
        currency: 'ユーロ',
        nameAnswer: 'おーすとりあきょうわこく',
        capitalAnswer: 'うぃーん'),
    const Country(
        area: '中東',
        name: 'オマーン国',
        englishName: 'Sultanate of Oman',
        capitalCity: 'マスカット',
        imageName: 'sultanate_of_oman',
        language: 'アラビア語（公用語）、英語も広く通用',
        currency: 'オマーン・リアル',
        nameAnswer: 'おまーんこく',
        capitalAnswer: 'ますかっと'),
    const Country(
        area: '欧州',
        name: 'オランダ王国',
        englishName: 'Kingdom of the Netherlands',
        capitalCity: 'アムステルダム',
        imageName: 'kingdom_of_the_netherlands',
        language: 'オランダ語',
        currency: 'ユーロ',
        nameAnswer: 'おらんだおうこく',
        capitalAnswer: 'あむすてるだむ'),
    const Country(
        area: 'アフリカ',
        name: 'ガーナ共和国',
        englishName: 'Republic of Ghana',
        capitalCity: 'アクラ',
        imageName: 'republic_of_ghana',
        language: '英語（公用語）、各民族語',
        currency: 'ガーナセディ',
        nameAnswer: 'がーなきょうわこく',
        capitalAnswer: 'あくら'),
    const Country(
        area: 'アフリカ',
        name: 'カーボベルデ共和国',
        englishName: 'Republic of Cabo Verde',
        capitalCity: 'プライア',
        imageName: 'republic_of_cabo_verde',
        language: 'ポルトガル語（公用語）、クレオール語',
        currency: 'カーボベルデ・エスクード',
        nameAnswer: 'かーぼべるできょうわこく',
        capitalAnswer: 'ぷらいあ'),
    const Country(
        area: '中南米',
        name: 'ガイアナ協同共和国',
        englishName: 'Co-operative Republic of Guyana',
        capitalCity: 'ジョージタウン',
        imageName: 'co-operative_republic_of_guyana',
        language: '英語（公用語）、ガイアナ・クレオール語など',
        currency: 'ガイアナ・ドル',
        nameAnswer: 'がいあなきょうどうきょうわこく',
        capitalAnswer: 'じょーじたうん'),
    const Country(
        area: '欧州',
        name: 'カザフスタン共和国',
        englishName: 'Republic of Kazakhstan',
        capitalCity: 'アスタナ',
        imageName: 'republic_of_kazakhstan',
        language: 'カザフ語（国語）、ロシア語（公用語）',
        currency: 'テンゲ',
        nameAnswer: 'かざふすたんきょうわこく',
        capitalAnswer: 'あすたな'),
    const Country(
        area: '中東',
        name: 'カタール国',
        englishName: 'State of Qatar',
        capitalCity: 'ドーハ',
        imageName: 'state_of_qatar',
        language: 'アラビア語',
        currency: 'カタール・リヤル',
        nameAnswer: 'かたーるこく',
        capitalAnswer: 'どーは'),
    const Country(
        area: '北米',
        name: 'カナダ',
        englishName: 'Canada',
        capitalCity: 'オタワ',
        imageName: 'canada',
        language: '英語、フランス語（ともに公用語）',
        currency: 'カナダ・ドル',
        nameAnswer: 'かなだ',
        capitalAnswer: 'おたわ'),
    const Country(
        area: 'アフリカ',
        name: 'ガボン共和国',
        englishName: 'Gabonese Republic',
        capitalCity: 'リーブルビル',
        imageName: 'gabonese_republic',
        language: 'フランス語（公用語）',
        currency: 'CFAフラン',
        nameAnswer: 'がぼんきょうわこく',
        capitalAnswer: 'りーぶるびる'),
    const Country(
        area: 'アフリカ',
        name: 'カメルーン共和国',
        englishName: 'Republic of Cameroon',
        capitalCity: 'ヤウンデ',
        imageName: 'republic_of_cameroon',
        language: 'フランス語、英語（ともにに公用語）、その他各部族語',
        currency: 'CFAフラン',
        nameAnswer: 'かめるーんきょうわこく',
        capitalAnswer: 'やうんで'),
    const Country(
        area: 'アフリカ',
        name: 'ガンビア共和国',
        englishName: 'Republic of The Gambia',
        capitalCity: 'バンジュール',
        imageName: 'republic_of_the_gambia',
        language: '英語（公用語）、マンディンゴ語、ウォロフ語、フラ語など',
        currency: 'ダラシ',
        nameAnswer: 'がんびあきょうわこく',
        capitalAnswer: 'ばんじゅーる'),
    const Country(
        area: 'アジア',
        name: 'カンボジア王国',
        englishName: 'Kingdom of Cambodia',
        capitalCity: 'プノンペン',
        imageName: 'kingdom_of_cambodia',
        language: 'クメール語',
        currency: 'リエル',
        nameAnswer: 'かんぼじあおうこく',
        capitalAnswer: 'ぷのんぺん'),
    const Country(
        area: '欧州',
        name: '北マケドニア共和国',
        englishName: 'Republic of North Macedonia',
        capitalCity: 'スコピエ',
        imageName: 'republic_of_north_macedonia',
        language: 'マケドニア語、アルバニア語',
        currency: 'マケドニア・デナル',
        nameAnswer: 'きたまけどにあきょうわこく',
        capitalAnswer: 'すこぴえ'),
    const Country(
        area: 'アフリカ',
        name: 'ギニア共和国',
        englishName: 'Republic of Guinea',
        capitalCity: 'コナクリ',
        imageName: 'republic_of_guinea',
        language: 'フランス語、各民族語（ブル、マリンケ、スースーなど）',
        currency: 'ギニア・フラン',
        nameAnswer: 'ぎにあきょうわこく',
        capitalAnswer: 'こなくり'),
    const Country(
        area: 'アフリカ',
        name: 'ギニアビサウ共和国',
        englishName: 'Republic of Guinea-Bissau',
        capitalCity: 'ビサウ',
        imageName: 'republic_of_guinea-bissau',
        language: 'ポルトガル語（公用語）',
        currency: 'CFAフラン',
        nameAnswer: 'ぎにあびさうきょうわこく',
        capitalAnswer: 'びさう'),
    const Country(
        area: '欧州',
        name: 'キプロス共和国',
        englishName: 'Republic of Cyprus',
        capitalCity: 'ニコシア',
        imageName: 'republic_of_cyprus',
        language: 'ギリシャ語、トルコ語（ともに公用語。この他、英語が広く用いられている。）',
        currency: 'ユーロ',
        nameAnswer: 'きぷろすきょうわこく',
        capitalAnswer: 'にこしあ'),
    const Country(
        area: '中南米',
        name: 'キューバ共和国',
        englishName: 'Republic of Cuba',
        capitalCity: 'ハバナ',
        imageName: 'republic_of_cuba',
        language: 'スペイン語',
        currency: 'キューバ・ペソ',
        nameAnswer: 'きゅーばきょうわこく',
        capitalAnswer: 'はばな'),
    const Country(
        area: '欧州',
        name: 'ギリシャ共和国',
        englishName: 'Hellenic Republic',
        capitalCity: 'アテネ',
        imageName: 'hellenic_republic',
        language: '現代ギリシャ語',
        currency: 'ユーロ',
        nameAnswer: 'ぎりしゃきょうわこく',
        capitalAnswer: 'あてね'),
    const Country(
        area: '大洋州',
        name: 'キリバス共和国',
        englishName: 'Republic of Kiribati',
        capitalCity: 'タラワ',
        imageName: 'republic_of_kiribati',
        language: 'キリバス語、英語（ともに公用語）',
        currency: 'オーストラリア・ドル',
        nameAnswer: 'きりばすきょうわこく',
        capitalAnswer: 'たらわ'),
    const Country(
        area: '欧州',
        name: 'キルギス共和国',
        englishName: 'Kyrgyz Republic',
        capitalCity: 'ビシュケク',
        imageName: 'kyrgyz_republic',
        language: 'キルギス語（国語）、ロシア語（公用語）',
        currency: 'ソム',
        nameAnswer: 'きるぎすきょうわこく',
        capitalAnswer: 'びしゅけく'),
    const Country(
        area: '中南米',
        name: 'グアテマラ共和国',
        englishName: 'Republic of Guatemala',
        capitalCity: 'グアテマラ市',
        imageName: 'republic_of_guatemala',
        language: 'スペイン語（公用語）、その他に２２のマヤ系言語など',
        currency: 'ケツァル',
        nameAnswer: 'ぐあてまらきょうわこく',
        capitalAnswer: 'ぐあてまらし'),
    const Country(
        area: '中東',
        name: 'クウェート国',
        englishName: 'State of Kuwait',
        capitalCity: 'クウェート',
        imageName: 'state_of_kuwait',
        language: 'アラビア語',
        currency: 'クウェート・ディナール',
        nameAnswer: 'くうぇーとこく',
        capitalAnswer: 'くうぇーと'),
    const Country(
        area: '大洋州',
        name: 'クック諸島',
        englishName: 'Cook Islands',
        capitalCity: 'アバルア（ラロトンガ島）',
        imageName: 'cook_islands',
        language: 'クック諸島マオリ語、英語（ともに公用語）',
        currency: 'ニュージーランド・ドル',
        nameAnswer: 'くっくしょとう',
        capitalAnswer: 'あばるあ（らろとんがとう）'),
    const Country(
        area: '中南米',
        name: 'グレナダ',
        englishName: 'Grenada',
        capitalCity: 'セントジョージズ',
        imageName: 'grenada',
        language: '英語（公用語）、グレナダ・クレオール語',
        currency: '東カリブ・ドル',
        nameAnswer: 'ぐれなだ',
        capitalAnswer: 'せんとじょーじず'),
    const Country(
        area: '欧州',
        name: 'クロアチア共和国',
        englishName: 'Republic of Croatia',
        capitalCity: 'ザグレブ',
        imageName: 'republic_of_croatia',
        language: 'クロアチア語（公用語）',
        currency: 'ユーロ',
        nameAnswer: 'くろあちあきょうわこく',
        capitalAnswer: 'ざぐれぶ'),
    const Country(
        area: 'アフリカ',
        name: 'ケニア共和国',
        englishName: 'Republic of Kenya',
        capitalCity: 'ナイロビ',
        imageName: 'republic_of_kenya',
        language: 'スワヒリ語、英語',
        currency: 'ケニア・シリング',
        nameAnswer: 'けにあきょうわこく',
        capitalAnswer: 'ないろび'),
    const Country(
        area: 'アフリカ',
        name: 'コートジボワール共和国',
        englishName: 'Republic of Cote d\'Ivoire',
        capitalCity: 'ヤムスクロ',
        imageName: 'republic_of_cote_divoire',
        language: 'フランス語（公用語）、各民族語',
        currency: 'CFAフラン',
        nameAnswer: 'こーとじぼわーるきょうわこく',
        capitalAnswer: 'やむすくろ'),
    const Country(
        area: '中南米',
        name: 'コスタリカ共和国',
        englishName: 'Republic of Costa Rica',
        capitalCity: 'サンホセ',
        imageName: 'republic_of_costa_rica',
        language: 'スペイン語',
        currency: 'コロン',
        nameAnswer: 'こすたりかきょうわこく',
        capitalAnswer: 'さんほせ'),
    const Country(
        area: '欧州',
        name: 'コソボ共和国',
        englishName: 'Republic of Kosovo',
        capitalCity: 'プリシュティナ',
        imageName: 'republic_of_kosovo',
        language: 'アルバニア語（アルバニア人）、セルビア語（セルビア人）など',
        currency: 'ユーロ',
        nameAnswer: 'こそぼきょうわこく',
        capitalAnswer: 'ぷりしゅてぃな'),
    const Country(
        area: 'アフリカ',
        name: 'コモロ連合',
        englishName: 'Union of Comoros',
        capitalCity: 'モロニ',
        imageName: 'union_of_comoros',
        language: 'フランス語、アラビア語、コモロ語（いずれも公用語）',
        currency: 'コモロ・フラン',
        nameAnswer: 'こもろれんごう',
        capitalAnswer: 'もろに'),
    const Country(
        area: '中南米',
        name: 'コロンビア共和国',
        englishName: 'Republic of Colombia',
        capitalCity: 'ボゴタ',
        imageName: 'republic_of_colombia',
        language: 'スペイン語',
        currency: 'ペソ',
        nameAnswer: 'ころんびあきょうわこく',
        capitalAnswer: 'ぼごた'),
    const Country(
        area: 'アフリカ',
        name: 'コンゴ共和国',
        englishName: 'Republic of Congo',
        capitalCity: 'ブラザビル',
        imageName: 'republic_of_congo',
        language: 'フランス語（公用語）、リンガラ語、キトゥバ語',
        currency: 'CFAフラン',
        nameAnswer: 'こんごきょうわこく',
        capitalAnswer: 'ぶらざびる'),
    const Country(
        area: 'アフリカ',
        name: 'コンゴ民主共和国',
        englishName: 'Democratic Republic of the Congo',
        capitalCity: 'キンシャサ',
        imageName: 'democratic_republic_of_the_congo',
        language: 'フランス語（公用語）、スワヒリ語、リンガラ語、チルバ語、キコンゴ語など',
        currency: 'コンゴ・フラン',
        nameAnswer: 'こんごみんしゅきょうわこく',
        capitalAnswer: 'きんしゃさ'),
    const Country(
        area: '中東',
        name: 'サウジアラビア王国',
        englishName: 'Kingdom of Saudi Arabia',
        capitalCity: 'リヤド',
        imageName: 'kingdom_of_saudi_arabia',
        language: 'アラビア語（公用語）',
        currency: 'サウジアラビア・リヤル',
        nameAnswer: 'さうじあらびあおうこく',
        capitalAnswer: 'りやど'),
    const Country(
        area: '大洋州',
        name: 'サモア独立国',
        englishName: 'Independent State of Samoa',
        capitalCity: 'アピア',
        imageName: 'independent_state_of_samoa',
        language: 'サモア語、英語（ともに公用語）',
        currency: 'サモア・タラ',
        nameAnswer: 'さもあ独立国',
        capitalAnswer: 'あぴあ'),
    const Country(
        area: 'アフリカ',
        name: 'サントメ・プリンシペ民主共和国',
        englishName: 'Democratic Republic of Sao Tome and Principe',
        capitalCity: 'サントメ',
        imageName: 'democratic_republic_of_sao_tome_and_principe',
        language: 'ポルトガル語',
        currency: 'ドブラ',
        nameAnswer: 'さんとめ・ぷりんしぺみんしゅきょうわこく',
        capitalAnswer: 'さんとめ'),
    const Country(
        area: 'アフリカ',
        name: 'ザンビア共和国',
        englishName: 'Republic of Zambia',
        capitalCity: 'ルサカ',
        imageName: 'republic_of_zambia',
        language: '英語（公用語）、ベンバ語、ニャンジァ語、トンガ語',
        currency: 'ザンビア・クワチャ',
        nameAnswer: 'ざんびあきょうわこく',
        capitalAnswer: 'るさか'),
    const Country(
        area: '欧州',
        name: 'サンマリノ共和国',
        englishName: 'Republic of San Marino',
        capitalCity: 'サンマリノ',
        imageName: 'republic_of_san_marino',
        language: 'イタリア語',
        currency: 'ユーロ',
        nameAnswer: 'さんまりのきょうわこく',
        capitalAnswer: 'さんまりの'),
    const Country(
        area: 'アフリカ',
        name: 'シエラレオネ共和国',
        englishName: 'Republic of Sierra Leone',
        capitalCity: 'フリータウン',
        imageName: 'republic_of_sierra_leone',
        language: '英語（公用語）、クリオ語、メンデ語、テムネ語など',
        currency: 'レオン',
        nameAnswer: 'しえられおねきょうわこく',
        capitalAnswer: 'ふりーたうん'),
    const Country(
        area: 'アフリカ',
        name: 'ジブチ共和国',
        englishName: 'Republic of Djibouti',
        capitalCity: 'ジブチ',
        imageName: 'republic_of_djibouti',
        language: 'アラビア語、フランス語',
        currency: 'ジブチ・フラン',
        nameAnswer: 'じぶちきょうわこく',
        capitalAnswer: 'じぶち'),
    const Country(
        area: '中南米',
        name: 'ジャマイカ',
        englishName: 'Jamaica',
        capitalCity: 'キングストン',
        imageName: 'jamaica',
        language: '英語（公用語）、ジャマイカ・クレオール語',
        currency: 'ジャマイカ・ドル',
        nameAnswer: 'じゃまいか',
        capitalAnswer: 'きんぐすとん'),
    const Country(
        area: '中東',
        name: 'シリア・アラブ共和国',
        englishName: 'Syrian Arab Republic',
        capitalCity: 'ダマスカス',
        imageName: 'syrian_arab_republic',
        language: 'アラビア語',
        currency: 'シリア・ポンド',
        nameAnswer: 'しりあ・あらぶきょうわこく',
        capitalAnswer: 'だますかす'),
    const Country(
        area: 'アジア',
        name: 'シンガポール共和国',
        englishName: 'Republic of Singapore',
        capitalCity: 'なし',
        imageName: 'republic_of_singapore',
        language: 'マレー語（国語）、英語、中国語、マレー語、タミール語（ともに公用語）',
        currency: 'シンガポール・ドル',
        nameAnswer: 'しんがぽーるきょうわこく',
        capitalAnswer: 'なし'),
    const Country(
        area: 'アフリカ',
        name: 'ジンバブエ共和国',
        englishName: 'Republic of Zimbabwe',
        capitalCity: 'ハラレ',
        imageName: 'republic_of_zimbabwe',
        language: '英語、ショナ語、ンデベレ語',
        currency: 'ジンバブエ・ドル',
        nameAnswer: 'じんばぶえきょうわこく',
        capitalAnswer: 'はられ'),
    const Country(
        area: '欧州',
        name: 'スイス連邦',
        englishName: 'Swiss Confederation',
        capitalCity: 'ベルン',
        imageName: 'swiss_confederation',
        language: 'ドイツ語、フランス語、イタリア語、ロマンシュ語',
        currency: 'スイス・フラン',
        nameAnswer: 'すいすれんぽう',
        capitalAnswer: 'べるん'),
    const Country(
        area: '欧州',
        name: 'スウェーデン王国',
        englishName: 'Kingdom of Sweden',
        capitalCity: 'ストックホルム',
        imageName: 'kingdom_of_sweden',
        language: 'スウェーデン語',
        currency: 'スウェーデン・クローナ',
        nameAnswer: 'すうぇーでんおうこく',
        capitalAnswer: 'すとっくほるむ'),
    const Country(
        area: 'アフリカ',
        name: 'スーダン共和国',
        englishName: 'The Republic of the Sudan',
        capitalCity: 'ハルツーム',
        imageName: 'the_republic_of_the_sudan',
        language: 'アラビア語（公用語）、英語も使用、その他、部族語多数',
        currency: 'スーダン・ポンド',
        nameAnswer: 'すーだんきょうわこく',
        capitalAnswer: 'はるつーむ'),
    const Country(
        area: '欧州',
        name: 'スペイン王国',
        englishName: 'Kingdom of Spain',
        capitalCity: 'マドリード',
        imageName: 'kingdom_of_spain',
        language: 'スペイン語',
        currency: 'ユーロ',
        nameAnswer: 'すぺいんおうこく',
        capitalAnswer: 'まどりーど'),
    const Country(
        area: '中南米',
        name: 'スリナム共和国',
        englishName: 'Republic of Suriname',
        capitalCity: 'パラマリボ',
        imageName: 'republic_of_suriname',
        language: 'オランダ語（公用語）、英語、スリナム語など',
        currency: 'スリナム・ドル',
        nameAnswer: 'すりなむきょうわこく',
        capitalAnswer: 'ぱらまりぼ'),
    const Country(
        area: 'アジア',
        name: 'スリランカ民主社会主義共和国',
        englishName: 'Democratic Socialist Republic of Sri Lanka',
        capitalCity: 'スリ・ジャヤワルダナプラ・コッテ',
        imageName: 'democratic_socialist_republic_of_sri_lanka',
        language: 'シンハラ語、タミル語（ともに公用語）、英語（連結語）',
        currency: 'ルピー',
        nameAnswer: 'すりらんかみんしゅしゃかいしゅぎきょうわこく',
        capitalAnswer: 'すり・じゃやわるだなぷら・こって'),
    const Country(
        area: '欧州',
        name: 'スロバキア共和国',
        englishName: 'Slovak Republic',
        capitalCity: 'ブラチスラバ',
        imageName: 'slovak_republic',
        language: 'スロバキア語',
        currency: 'ユーロ',
        nameAnswer: 'すろばきあきょうわこく',
        capitalAnswer: 'ぶらちすらば'),
    const Country(
        area: '欧州',
        name: 'スロベニア共和国',
        englishName: 'Republic of Slovenia',
        capitalCity: 'リュブリャナ',
        imageName: 'republic_of_slovenia',
        language: 'スロベニア語',
        currency: 'ユーロ',
        nameAnswer: 'すろべにあきょうわこく',
        capitalAnswer: 'りゅぶりゃな'),
    const Country(
        area: 'アフリカ',
        name: 'セーシェル共和国',
        englishName: 'Republic of Seychelles',
        capitalCity: 'ヴィクトリア',
        imageName: 'republic_of_seychelles',
        language: '英語、フランス語、クレオール語',
        currency: 'セーシェル・ルピー',
        nameAnswer: 'せーしぇるきょうわこく',
        capitalAnswer: 'ゔぃくとりあ'),
    const Country(
        area: 'アフリカ',
        name: '赤道ギニア共和国',
        englishName: 'Republic of Equatorial Guinea',
        capitalCity: 'マラボ',
        imageName: 'republic_of_equatorial_guinea',
        language: 'スペイン語（公用語）、フランス語（第2公用語）、ポルトガル語（第3公用語）、ファン語、ブビ語',
        currency: 'CFAフラン',
        nameAnswer: 'せきどうぎにあきょうわこく',
        capitalAnswer: 'まらぼ'),
    const Country(
        area: 'アフリカ',
        name: 'セネガル共和国',
        englishName: 'Republic of Senegal',
        capitalCity: 'ダカール',
        imageName: 'republic_of_senegal',
        language: 'フランス語（公用語）、ウォロフ語など各民族語',
        currency: 'CFAフラン',
        nameAnswer: 'せねがるきょうわこく',
        capitalAnswer: 'だかーる'),
    const Country(
        area: '欧州',
        name: 'セルビア共和国',
        englishName: 'Republic of Serbia',
        capitalCity: 'ベオグラード',
        imageName: 'republic_of_serbia',
        language: 'セルビア語（公用語）、ハンガリー語など',
        currency: 'ディナール',
        nameAnswer: 'せるびあきょうわこく',
        capitalAnswer: 'べおぐらーど'),
    const Country(
        area: '中南米',
        name: 'セントクリストファー・ネービス',
        englishName: 'Saint Christopher and Nevis',
        capitalCity: 'バセテール',
        imageName: 'saint_christopher_and_nevis',
        language: '英語（公用語）',
        currency: '東カリブ・ドル',
        nameAnswer: 'せんとくりすとふぁー・ねーびす',
        capitalAnswer: 'ばせてーる'),
    const Country(
        area: '中南米',
        name: 'セントビンセント及びグレナディーン諸島',
        englishName: 'Saint Vincent and the Grenadines',
        capitalCity: 'キングスタウン',
        imageName: 'saint_vincent_and_the_grenadines',
        language: '英語（公用語）、セントビンセント・クレオール語',
        currency: '東カリブ・ドル',
        nameAnswer: 'せんとびんせんとおよびぐれなでぃーんしょとう',
        capitalAnswer: 'きんぐすたうん'),
    const Country(
        area: '中南米',
        name: 'セントルシア',
        englishName: 'Saint Lucia',
        capitalCity: 'カストリーズ',
        imageName: 'saint_lucia',
        language: '英語（公用語）、セントルシア・クレオール語',
        currency: '東カリブ・ドル',
        nameAnswer: 'せんとるしあ',
        capitalAnswer: 'かすとりーず'),
    const Country(
        area: 'アフリカ',
        name: 'ソマリア連邦共和国',
        englishName: 'Federal Republic of Somalia',
        capitalCity: 'モガディシュ',
        imageName: 'federal_republic_of_somalia',
        language: 'ソマリ語（公用語）、アラビア語（第2公用語）',
        currency: 'ソマリア・シリング',
        nameAnswer: 'そまりあれんぽうきょうわこく',
        capitalAnswer: 'もがでぃしゅ'),
    const Country(
        area: '大洋州',
        name: 'ソロモン諸島',
        englishName: 'Solomon Islands',
        capitalCity: 'ホニアラ',
        imageName: 'solomon_islands',
        language: '英語（公用語）、ピジン英語（共通語）',
        currency: 'ソロモン・ドル',
        nameAnswer: 'そろもんしょとう',
        capitalAnswer: 'ほにあら'),
    const Country(
        area: 'アジア',
        name: 'タイ王国',
        englishName: 'Kingdom of Thailand',
        capitalCity: 'バンコク',
        imageName: 'kingdom_of_thailand',
        language: 'タイ語',
        currency: 'バーツ',
        nameAnswer: 'たいおうこく',
        capitalAnswer: 'ばんこく'),
    const Country(
        area: 'アジア',
        name: '大韓民国',
        englishName: 'Republic of Korea',
        capitalCity: 'ソウル',
        imageName: 'republic_of_korea',
        language: '韓国語',
        currency: 'ウォン',
        nameAnswer: 'だいかんみんこく',
        capitalAnswer: 'そうる'),
    const Country(
        area: '欧州',
        name: 'タジキスタン共和国',
        englishName: 'Republic of Tajikistan',
        capitalCity: 'ドゥシャンベ',
        imageName: 'republic_of_tajikistan',
        language: 'タジク語（公用語）、ロシア語も広く使われている',
        currency: 'ソモニ',
        nameAnswer: 'たじきすたんきょうわこく',
        capitalAnswer: 'どぅしゃんべ'),
    const Country(
        area: 'アフリカ',
        name: 'タンザニア連合共和国',
        englishName: 'United Republic of Tanzania',
        capitalCity: 'ドドマ',
        imageName: 'united_republic_of_tanzania',
        language: 'スワヒリ語（国語）、英語（公用語）',
        currency: 'タンザニア・シリング',
        nameAnswer: 'たんざにあれんごうきょうわこく',
        capitalAnswer: 'どどま'),
    const Country(
        area: '欧州',
        name: 'チェコ共和国',
        englishName: 'Czech Republic',
        capitalCity: 'プラハ',
        imageName: 'czech_republic',
        language: 'チェコ語',
        currency: 'チェコ・コルナ',
        nameAnswer: 'ちぇこきょうわこく',
        capitalAnswer: 'ぷらは'),
    const Country(
        area: 'アフリカ',
        name: 'チャド共和国',
        englishName: 'Republic of Chad',
        capitalCity: 'ウンジャメナ',
        imageName: 'republic_of_chad',
        language: 'フランス語、アラビア語（ともに公用語）、部族語130以上',
        currency: 'CFAフラン',
        nameAnswer: 'ちゃどきょうわこく',
        capitalAnswer: 'うんじゃめな'),
    const Country(
        area: 'アフリカ',
        name: '中央アフリカ共和国',
        englishName: 'Central African Republic',
        capitalCity: 'バンギ',
        imageName: 'central_african_republic',
        language: 'フランス語（公用語）、サンゴ語（公用語、国語）、部族語',
        currency: 'CFAフラン',
        nameAnswer: 'ちゅうおうあふりかきょうわこく',
        capitalAnswer: 'ばんぎ'),
    const Country(
        area: 'アジア',
        name: '中華人民共和国',
        englishName: 'People\'s Republic of China',
        capitalCity: '北京',
        imageName: 'peoples_republic_of_china',
        language: '中国語',
        currency: '人民元',
        nameAnswer: 'ちゅうかじんみんきょうわこく',
        capitalAnswer: 'ぺきん'),
    const Country(
        area: 'アフリカ',
        name: 'チュニジア共和国',
        englishName: 'Republic of Tunisia',
        capitalCity: 'チュニス',
        imageName: 'republic_of_tunisia',
        language: 'アラビア語（公用語）、フランス語（国民の間で広く用いられている）',
        currency: 'チュニジア・ディナール',
        nameAnswer: 'ちゅにじあきょうわこく',
        capitalAnswer: 'ちゅにす'),
    const Country(
        area: '中南米',
        name: 'チリ共和国',
        englishName: 'Republic of Chile',
        capitalCity: 'サンティアゴ',
        imageName: 'republic_of_chile',
        language: 'スペイン語',
        currency: 'ペソ',
        nameAnswer: 'ちりきょうわこく',
        capitalAnswer: 'さんてぃあご'),
    const Country(
        area: '大洋州',
        name: 'ツバル',
        englishName: 'Tuvalu',
        capitalCity: 'フナフティ',
        imageName: 'tuvalu',
        language: '英語、ツバル語',
        currency: 'オーストラリア・ドル',
        nameAnswer: 'つばる',
        capitalAnswer: 'ふなふてぃ'),
    const Country(
        area: '欧州',
        name: 'デンマーク王国',
        englishName: 'Kingdom of Denmark',
        capitalCity: 'コペンハーゲン',
        imageName: 'kingdom_of_denmark',
        language: 'デンマーク語',
        currency: 'デンマーク・クローネ',
        nameAnswer: 'でんまーくおうこく',
        capitalAnswer: 'こぺんはーげん'),
    const Country(
        area: '欧州',
        name: 'ドイツ連邦共和国',
        englishName: 'Federal Republic of Germany',
        capitalCity: 'ベルリン',
        imageName: 'federal_republic_of_germany',
        language: 'ドイツ語',
        currency: 'ユーロ',
        nameAnswer: 'どいつれんぽうきょうわこく',
        capitalAnswer: 'べるりん'),
    const Country(
        area: 'アフリカ',
        name: 'トーゴ共和国',
        englishName: 'Republic of Togo',
        capitalCity: 'ロメ',
        imageName: 'republic_of_togo',
        language: 'フランス語（公用語）、エヴェ語、カビエ語など',
        currency: 'CFAフラン（注３）',
        nameAnswer: 'とーごきょうわこく',
        capitalAnswer: 'ろめ'),
    const Country(
        area: '中南米',
        name: 'ドミニカ国',
        englishName: 'Commonwealth of Dominica',
        capitalCity: 'ロゾー',
        imageName: 'commonwealth_of_dominica',
        language: '英語（公用語）、フランス語系パトワ語',
        currency: '東カリブ・ドル',
        nameAnswer: 'どみにかこく',
        capitalAnswer: 'ろぞー'),
    const Country(
        area: '中南米',
        name: 'ドミニカ共和国',
        englishName: 'Dominican Republic',
        capitalCity: 'サントドミンゴ',
        imageName: 'dominican_republic',
        language: 'スペイン語',
        currency: 'ドミニカ・ペソ',
        nameAnswer: 'どみにかきょうわこく',
        capitalAnswer: 'さんとどみんご'),
    const Country(
        area: '中南米',
        name: 'トリニダード・トバゴ共和国',
        englishName: 'Republic of Trinidad and Tobago',
        capitalCity: 'ポート・オブ・スペイン',
        imageName: 'republic_of_trinidad_and_tobago',
        language: '英語（公用語）、ヒンディー語、フランス語、スペイン語、トリニダード・クレオール語など',
        currency: 'トリニダード・トバゴ・ドル',
        nameAnswer: 'とりにだーど・とばごきょうわこく',
        capitalAnswer: 'ぽーと・おぶ・すぺいん'),
    const Country(
        area: '欧州',
        name: 'トルクメニスタン',
        englishName: 'Turkmenistan',
        capitalCity: 'アシガバット',
        imageName: 'turkmenistan',
        language: 'トルクメン語（公用語）、ロシア語も広く使われている',
        currency: 'マナト',
        nameAnswer: 'とるくめにすたん',
        capitalAnswer: 'あしがばっと'),
    const Country(
        area: '中東',
        name: 'トルコ共和国',
        englishName: 'Republic of Türkiye',
        capitalCity: 'アンカラ',
        imageName: 'republic_of_türkiye',
        language: 'トルコ語（公用語）',
        currency: 'トルコ・リラ',
        nameAnswer: 'とるこきょうわこく',
        capitalAnswer: 'あんから'),
    const Country(
        area: '大洋州',
        name: 'トンガ王国',
        englishName: 'Kingdom of Tonga',
        capitalCity: 'ヌクアロファ',
        imageName: 'kingdom_of_tonga',
        language: 'トンガ語、英語（ともに公用語）',
        currency: 'パアンガ',
        nameAnswer: 'とんがおうこく',
        capitalAnswer: 'ぬくあろふぁ'),
    const Country(
        area: 'アフリカ',
        name: 'ナイジェリア連邦共和国',
        englishName: 'Federal Republic of Nigeria',
        capitalCity: 'アブジャ',
        imageName: 'federal_republic_of_nigeria',
        language: '英語（公用語）、各民族語（ハウサ語、ヨルバ語、イボ語など）',
        currency: 'ナイラ',
        nameAnswer: 'ないじぇりあれんぽうきょうわこく',
        capitalAnswer: 'あぶじゃ'),
    const Country(
        area: '大洋州',
        name: 'ナウル共和国',
        englishName: 'Republic of Nauru',
        capitalCity: 'ヤレン',
        imageName: 'republic_of_nauru',
        language: '英語（公用語）、ナウル語',
        currency: 'オーストラリア・ドル',
        nameAnswer: 'なうるきょうわこく',
        capitalAnswer: 'やれん'),
    const Country(
        area: 'アフリカ',
        name: 'ナミビア共和国',
        englishName: 'Republic of Namibia',
        capitalCity: 'ウィントフック',
        imageName: 'republic_of_namibia',
        language: '英語（公用語）、アフリカーンス語、ドイツ語、その他部族語',
        currency: 'ナミビア・ドル',
        nameAnswer: 'なみびあきょうわこく',
        capitalAnswer: 'うぃんとふっく'),
    const Country(
        area: '大洋州',
        name: 'ニウエ',
        englishName: 'Niue',
        capitalCity: 'アロフィ',
        imageName: 'niue',
        language: 'ニウエ語（ポリネシア語系）、英語',
        currency: 'ニュージーランド・ドル',
        nameAnswer: 'にうえ',
        capitalAnswer: 'あろふぃ'),
    const Country(
        area: '中南米',
        name: 'ニカラグア共和国',
        englishName: 'Republic of Nicaragua',
        capitalCity: 'マナグア',
        imageName: 'republic_of_nicaragua',
        language: 'スペイン語',
        currency: 'コルドバ',
        nameAnswer: 'にからぐあきょうわこく',
        capitalAnswer: 'まなぐあ'),
    const Country(
        area: 'アフリカ',
        name: 'ニジェール共和国',
        englishName: 'Republic of Niger',
        capitalCity: 'ニアメ',
        imageName: 'republic_of_niger',
        language: 'フランス語（公用語）、ハウサ語など',
        currency: 'CFAフラン',
        nameAnswer: 'にじぇーるきょうわこく',
        capitalAnswer: 'にあめ'),
    const Country(
        area: 'アジア',
        name: '日本',
        englishName: 'Japan',
        capitalCity: '東京',
        imageName: 'japan',
        language: '日本語',
        currency: '円',
        nameAnswer: 'にほん',
        capitalAnswer: 'とうきょう'),
    const Country(
        area: '大洋州',
        name: 'ニュージーランド',
        englishName: 'New Zealand',
        capitalCity: 'ウェリントン',
        imageName: 'new_zealand',
        language: '英語、マオリ語',
        currency: 'ニュージーランド・ドル',
        nameAnswer: 'にゅーじーらんど',
        capitalAnswer: 'うぇりんとん'),
    const Country(
        area: 'アジア',
        name: 'ネパール',
        englishName: 'Nepal',
        capitalCity: 'カトマンズ',
        imageName: 'nepal',
        language: 'ネパール語',
        currency: 'ネパール・ルピー',
        nameAnswer: 'ねぱーる',
        capitalAnswer: 'かとまんず'),
    const Country(
        area: '欧州',
        name: 'ノルウェー王国',
        englishName: 'Kingdom of Norway',
        capitalCity: 'オスロ',
        imageName: 'kingdom_of_norway',
        language: 'ノルウェー語、サーミ語',
        currency: 'ノルウェー・クローネ',
        nameAnswer: 'のるうぇーおうこく',
        capitalAnswer: 'おすろ'),
    const Country(
        area: '中東',
        name: 'バーレーン王国',
        englishName: 'Kingdom of Bahrain',
        capitalCity: 'マナーマ市',
        imageName: 'kingdom_of_bahrain',
        language: 'アラビア語',
        currency: 'バーレーン・ディナール',
        nameAnswer: 'ばーれーんおうこく',
        capitalAnswer: 'まなーまし'),
    const Country(
        area: '中南米',
        name: 'ハイチ共和国',
        englishName: 'Republic of Haiti',
        capitalCity: 'ポルトープランス',
        imageName: 'republic_of_haiti',
        language: 'フランス語、ハイチ・クレオール語（ともに公用語）',
        currency: 'グルド',
        nameAnswer: 'はいちきょうわこく',
        capitalAnswer: 'ぽるとーぷらんす'),
    const Country(
        area: 'アジア',
        name: 'パキスタン・イスラム共和国',
        englishName: 'Islamic Republic of Pakistan',
        capitalCity: 'イスラマバード',
        imageName: 'islamic_republic_of_pakistan',
        language: 'ウルドゥー語（国語）、英語（公用語）',
        currency: 'パキスタン・ルピー',
        nameAnswer: 'ぱきすたん・いすらむきょうわこく',
        capitalAnswer: 'いすらまばーど'),
    const Country(
        area: '欧州',
        name: 'バチカン',
        englishName: 'Vatican City State',
        capitalCity: '',
        imageName: 'vatican_city_state',
        language: 'ラテン語（公用語）。ただし、外交用にはフランス語、通常業務ではイタリア語を使うことが多い。',
        currency: 'ユーロ',
        nameAnswer: 'ばちかん',
        capitalAnswer: ''),
    const Country(
        area: '中南米',
        name: 'パナマ共和国',
        englishName: 'Republic of Panama',
        capitalCity: 'パナマシティー',
        imageName: 'republic_of_panama',
        language: 'スペイン語',
        currency: 'バルボア',
        nameAnswer: 'ぱなまきょうわこく',
        capitalAnswer: 'ぱなましてぃー'),
    const Country(
        area: '大洋州',
        name: 'バヌアツ共和国',
        englishName: 'Republic of Vanuatu',
        capitalCity: 'ポートビラ',
        imageName: 'republic_of_vanuatu',
        language: 'ビスラマ語（ピジン英語）、英語、フランス語（ともに公用語）',
        currency: 'バツ',
        nameAnswer: 'ばぬあつきょうわこく',
        capitalAnswer: 'ぽーとびら'),
    const Country(
        area: '中南米',
        name: 'バハマ国',
        englishName: 'Commonwealth of The Bahamas',
        capitalCity: 'ナッソー',
        imageName: 'commonwealth_of_the_bahamas',
        language: '英語（公用語）',
        currency: 'バハマ・ドル',
        nameAnswer: 'ばはまこく',
        capitalAnswer: 'なっそー'),
    const Country(
        area: '大洋州',
        name: 'パプアニューギニア独立国',
        englishName: 'Independent State of Papua New Guinea',
        capitalCity: 'ポートモレスビー',
        imageName: 'independent_state_of_papua_new_guinea',
        language: '英語（公用語）、ピジン英語、モツ語など',
        currency: 'キナ及びトヤ',
        nameAnswer: 'ぱぷあにゅーぎにあどくりつこく',
        capitalAnswer: 'ぽーともれすびー'),
    const Country(
        area: '大洋州',
        name: 'パラオ共和国',
        englishName: 'Republic of Palau',
        capitalCity: 'マルキョク',
        imageName: 'republic_of_palau',
        language: 'パラオ語、英語',
        currency: '米ドル',
        nameAnswer: 'ぱらおきょうわこく',
        capitalAnswer: 'まるきょく'),
    const Country(
        area: '中南米',
        name: 'パラグアイ共和国',
        englishName: 'Republic of Paraguay',
        capitalCity: 'アスンシオン',
        imageName: 'republic_of_paraguay',
        language: 'スペイン語、グアラニー語（ともに公用語）',
        currency: 'グアラニー',
        nameAnswer: 'ぱらぐあいきょうわこく',
        capitalAnswer: 'あすんしおん'),
    const Country(
        area: '中南米',
        name: 'バルバドス',
        englishName: 'Barbados',
        capitalCity: 'ブリッジタウン',
        imageName: 'barbados',
        language: '英語（公用語）',
        currency: 'バルバドス・ドル',
        nameAnswer: 'ばるばどす',
        capitalAnswer: 'ぶりっじたうん'),
    const Country(
        area: '欧州',
        name: 'ハンガリー',
        englishName: 'Hungary',
        capitalCity: 'ブダペスト',
        imageName: 'hungary',
        language: 'ハンガリー語',
        currency: 'フォリント',
        nameAnswer: 'はんがりー',
        capitalAnswer: 'ぶだぺすと'),
    const Country(
        area: 'アジア',
        name: 'バングラデシュ人民共和国',
        englishName: "People's Republic of Bangladesh",
        capitalCity: 'ダッカ',
        imageName: 'peoples_republic_of_bangladesh',
        language: 'ベンガル語（国語）',
        currency: 'タカ',
        nameAnswer: 'ばんぐらでしゅじんみんきょうわこく',
        capitalAnswer: 'だっか'),
    const Country(
        area: 'アジア',
        name: '東ティモール民主共和国',
        englishName: 'The Democratic Republic of Timor-Leste',
        capitalCity: 'ディリ',
        imageName: 'the_democratic_republic_of_timor-leste',
        language: 'テトゥン語、ポルトガル語（ともに公用語）、インドネシア語、英語（ともに実用語）',
        currency: '米ドル',
        nameAnswer: 'ひがしてぃもーるみんしゅきょうわこく',
        capitalAnswer: 'でぃり'),
    const Country(
        area: '大洋州',
        name: 'フィジー共和国',
        englishName: 'Republic of Fiji',
        capitalCity: 'スバ',
        imageName: 'republic_of_fiji',
        language: '英語（公用語）、フィジー語、ヒンディー語',
        currency: 'フィジー・ドル',
        nameAnswer: 'ふぃじーきょうわこく',
        capitalAnswer: 'すば'),
    const Country(
        area: 'アジア',
        name: 'フィリピン共和国',
        englishName: 'Republic of the Philippines',
        capitalCity: 'マニラ',
        imageName: 'republic_of_the_philippines',
        language: 'フィリピノ語（国語）、フィリピノ語、英語（ともに公用語）',
        currency: 'ペソ',
        nameAnswer: 'ふぃりぴんきょうわこく',
        capitalAnswer: 'まにら'),
    const Country(
        area: '欧州',
        name: 'フィンランド共和国',
        englishName: 'Republic of Finland',
        capitalCity: 'ヘルシンキ',
        imageName: 'republic_of_finland',
        language: 'フィンランド語、スウェーデン語',
        currency: 'ユーロ',
        nameAnswer: 'ふぃんらんどきょうわこく',
        capitalAnswer: 'へるしんき'),
    const Country(
        area: 'アジア',
        name: 'ブータン王国',
        englishName: 'Kingdom of Bhutan',
        capitalCity: 'ティンプー',
        imageName: 'kingdom_of_bhutan',
        language: 'ゾンカ語（公用語）など',
        currency: 'ニュルタム',
        nameAnswer: 'ぶーたんおうこく',
        capitalAnswer: 'てぃんぷー'),
    const Country(
        area: '中南米',
        name: 'ブラジル連邦共和国',
        englishName: 'Federative Republic of Brazil',
        capitalCity: 'ブラジリア',
        imageName: 'federative_republic_of_brazil',
        language: 'ポルトガル語',
        currency: 'レアル',
        nameAnswer: 'ぶらじるれんぽうきょうわこく',
        capitalAnswer: 'ぶらじりあ'),
    const Country(
        area: '欧州',
        name: 'フランス共和国',
        englishName: 'French Republic',
        capitalCity: 'パリ',
        imageName: 'french_republic',
        language: 'フランス語',
        currency: 'ユーロ',
        nameAnswer: 'ふらんすきょうわこく',
        capitalAnswer: 'ぱり'),
    const Country(
        area: '欧州',
        name: 'ブルガリア共和国',
        englishName: 'Republic of Bulgaria',
        capitalCity: 'ソフィア',
        imageName: 'republic_of_bulgaria',
        language: 'ブルガリア語',
        currency: 'レフ',
        nameAnswer: 'ぶるがりあきょうわこく',
        capitalAnswer: 'そふぃあ'),
    const Country(
        area: 'アフリカ',
        name: 'ブルキナファソ',
        englishName: 'Burkina Faso',
        capitalCity: 'ワガドゥグ',
        imageName: 'burkina_faso',
        language: 'フランス語、モレ語、ディウラ語、グルマンチェ語、プル（フラニ）語など約60言語',
        currency: 'CFAフラン',
        nameAnswer: 'ぶるきなふぁそ',
        capitalAnswer: 'わがどぅぐ'),
    const Country(
        area: 'アジア',
        name: 'ブルネイ・ダルサラーム国',
        englishName: 'Brunei Darussalam',
        capitalCity: 'バンダル・スリ・ブガワン',
        imageName: 'brunei_darussalam',
        language: 'マレー語（公用語）、英語は広く通用し、華人の間では中国語もある程度用いられている。',
        currency: 'ブルネイ・ドル',
        nameAnswer: 'ぶるねい・だるさらーむこく',
        capitalAnswer: 'ばんだる・すり・ぶがわん'),
    const Country(
        area: 'アフリカ',
        name: 'ブルンジ共和国',
        englishName: 'Republic of Burundi',
        capitalCity: 'ブジュンブラ',
        imageName: 'republic_of_burundi',
        language: 'フランス語、キルンジ語（ともに公用語）',
        currency: 'ブルンジ・フラン',
        nameAnswer: 'ぶるんじきょうわこく',
        capitalAnswer: 'ぶじゅんぶら'),
    const Country(
        area: 'アジア',
        name: 'ベトナム社会主義共和国',
        englishName: 'Socialist Republic of Viet Nam',
        capitalCity: 'ハノイ',
        imageName: 'socialist_republic_of_viet_nam',
        language: 'ベトナム語',
        currency: 'ドン',
        nameAnswer: 'べとなむしゃかいしゅぎきょうわこく',
        capitalAnswer: 'はのい'),
    const Country(
        area: 'アフリカ',
        name: 'ベナン共和国',
        englishName: 'Republic of Benin',
        capitalCity: 'ポルトノボ',
        imageName: 'republic_of_benin',
        language: 'フランス語（公用語）',
        currency: 'CFAフラン',
        nameAnswer: 'べなんきょうわこく',
        capitalAnswer: 'ぽるとのぼ'),
    const Country(
        area: '中南米',
        name: 'ベネズエラ・ボリバル共和国',
        englishName: 'Bolivarian Republic of Venezuela',
        capitalCity: 'カラカス',
        imageName: 'bolivarian_republic_of_venezuela',
        language: 'スペイン語（公用語）、先住民族の諸言語',
        currency: 'ボリバル',
        nameAnswer: 'べねずえら・ぼりばるきょうわこく',
        capitalAnswer: 'からかす'),
    const Country(
        area: '欧州',
        name: 'ベラルーシ共和国',
        englishName: 'Republic of Belarus',
        capitalCity: 'ミンスク',
        imageName: 'republic_of_belarus',
        language: 'ベラルーシ語、ロシア語（ともに公用語）',
        currency: 'ベラルーシ・ルーブル',
        nameAnswer: 'べらるーしきょうわこく',
        capitalAnswer: 'みんすく'),
    const Country(
        area: '中南米',
        name: 'ベリーズ',
        englishName: 'Belize',
        capitalCity: 'ベルモパン',
        imageName: 'belize',
        language: '英語（公用語）、スペイン語、ベリーズ・クレオール語、モパン語など',
        currency: 'ベリーズ・ドル',
        nameAnswer: 'べりーず',
        capitalAnswer: 'べるもぱん'),
    const Country(
        area: '中南米',
        name: 'ペルー共和国',
        englishName: 'Republic of Peru',
        capitalCity: 'リマ',
        imageName: 'republic_of_peru',
        language: 'スペイン語（他にケチュア語、アイマラ語など）',
        currency: 'ソル',
        nameAnswer: 'ぺるーきょうわこく',
        capitalAnswer: 'りま'),
    const Country(
        area: '欧州',
        name: 'ベルギー王国',
        englishName: 'Kingdom of Belgium',
        capitalCity: 'ブリュッセル',
        imageName: 'kingdom_of_belgium',
        language: 'オランダ語（フラマン語）、フランス語、ドイツ語',
        currency: 'ユーロ',
        nameAnswer: 'べるぎーおうこく',
        capitalAnswer: 'ぶりゅっせる'),
    const Country(
        area: '欧州',
        name: 'ポーランド共和国',
        englishName: 'Republic of Poland',
        capitalCity: 'ワルシャワ',
        imageName: 'republic_of_poland',
        language: 'ポーランド語',
        currency: 'ズロチ',
        nameAnswer: 'ぽーらんどきょうわこく',
        capitalAnswer: 'わるしゃわ'),
    const Country(
        area: '欧州',
        name: 'ボスニア・ヘルツェゴビナ',
        englishName: 'Bosnia and Herzegovina',
        capitalCity: 'サラエボ',
        imageName: 'bosnia_and_herzegovina',
        language: 'ボスニア語、セルビア語、クロアチア語',
        currency: '兌換マルク',
        nameAnswer: 'ぼすにあ・へるつぇごびな',
        capitalAnswer: 'さらえぼ'),
    const Country(
        area: '中南米',
        name: 'ボリビア多民族国',
        englishName: 'Plurinational State of Bolivia',
        capitalCity: 'ラパス',
        imageName: 'plurinational_state_of_bolivia',
        language: 'スペイン語及びケチュア語、アイマラ語を中心に先住民言語３６言語',
        currency: 'ボリビアーノス',
        nameAnswer: 'ぼりびあたみんぞくこく',
        capitalAnswer: 'らぱす'),
    const Country(
        area: '欧州',
        name: 'ポルトガル共和国',
        englishName: 'Portuguese Republic',
        capitalCity: 'リスボン',
        imageName: 'portuguese_republic',
        language: 'ポルトガル語',
        currency: 'ユーロ',
        nameAnswer: 'ぽるとがるきょうわこく',
        capitalAnswer: 'りすぼん'),
    const Country(
        area: '中南米',
        name: 'ホンジュラス共和国',
        englishName: 'Republic of Honduras',
        capitalCity: 'テグシガルパ',
        imageName: 'republic_of_honduras',
        language: 'スペイン語',
        currency: 'レンピラ',
        nameAnswer: 'ほんじゅらすきょうわこく',
        capitalAnswer: 'てぐしがるぱ'),
    const Country(
        area: '大洋州',
        name: 'マーシャル諸島共和国',
        englishName: 'Republic of the Marshall Islands',
        capitalCity: 'マジュロ',
        imageName: 'republic_of_the_marshall_islands',
        language: 'マーシャル語、英語',
        currency: '米ドル',
        nameAnswer: 'まーしゃるしょとうきょうわこく',
        capitalAnswer: 'まじゅろ'),
    const Country(
        area: 'アフリカ',
        name: 'マダガスカル共和国',
        englishName: 'Republic of Madagascar',
        capitalCity: 'アンタナナリボ',
        imageName: 'republic_of_madagascar',
        language: 'マダガスカル語、フランス語（ともに公用語）',
        currency: 'アリアリ',
        nameAnswer: 'まだがすかるきょうわこく',
        capitalAnswer: 'あんたななりぼ'),
    const Country(
        area: 'アフリカ',
        name: 'マラウイ共和国',
        englishName: 'Republic of Malawi',
        capitalCity: 'リロングウェ',
        imageName: 'republic_of_malawi',
        language: 'チェワ語、英語（ともに公用語）、各民族語',
        currency: 'マラウイ・クワチャ',
        nameAnswer: 'まらうぃきょうわこく',
        capitalAnswer: 'りろんぐうぇ'),
    const Country(
        area: 'アフリカ',
        name: 'マリ共和国',
        englishName: 'Republic of Mali',
        capitalCity: 'バマコ',
        imageName: 'republic_of_mali',
        language: 'フランス語（公用語）、バンバラ語、フルフルデ語、マリンケ語など',
        currency: 'CFAフラン',
        nameAnswer: 'まりきょうわこく',
        capitalAnswer: 'ばまこ'),
    const Country(
        area: '欧州',
        name: 'マルタ共和国',
        englishName: 'Republic of Malta',
        capitalCity: 'バレッタ',
        imageName: 'republic_of_malta',
        language: 'マルタ語、英語（ともに公用語）',
        currency: 'ユーロ',
        nameAnswer: 'まるたきょうわこく',
        capitalAnswer: 'ばれった'),
    const Country(
        area: 'アジア',
        name: 'マレーシア',
        englishName: 'Malaysia',
        capitalCity: 'クアラルンプール',
        imageName: 'malaysia',
        language: 'マレー語（国語）、中国語、タミール語、英語',
        currency: 'リンギット',
        nameAnswer: 'まれーしあ',
        capitalAnswer: 'くあらるんぷーる'),
    const Country(
        area: '大洋州',
        name: 'ミクロネシア連邦',
        englishName: 'Federated States of Micronesia',
        capitalCity: 'パリキール',
        imageName: 'federated_states_of_micronesia',
        language: '英語、現地の8言語',
        currency: '米ドル',
        nameAnswer: 'みくろねしあれんぽう',
        capitalAnswer: 'ぱりきーる'),
    const Country(
        area: 'アフリカ',
        name: '南アフリカ共和国',
        englishName: 'Republic of South Africa',
        capitalCity: 'プレトリア',
        imageName: 'republic_of_south_africa',
        language: '英語、アフリカーンス語、バンツー諸語（ズールー語、ソト語ほか）の合計11が公用語',
        currency: 'ランド',
        nameAnswer: 'みなみあふりかきょうわこく',
        capitalAnswer: 'ぷれとりあ'),
    const Country(
        area: 'アフリカ',
        name: '南スーダン共和国',
        englishName: 'The Republic of South Sudan',
        capitalCity: 'ジュバ',
        imageName: 'the_republic_of_south_sudan',
        language: '英語（公用語）、アラビア語、その他部族語多数',
        currency: '南スーダン・ポンド',
        nameAnswer: 'みなみすーだんきょうわこく',
        capitalAnswer: 'じゅば'),
    const Country(
        area: 'アジア',
        name: 'ミャンマー連邦共和国',
        englishName: 'Republic of the Union of Myanmar',
        capitalCity: 'ネーピードー',
        imageName: 'republic_of_the_union_of_myanmar',
        language: 'ミャンマー語（公用語）、シャン語、カレン語など',
        currency: 'チャット',
        nameAnswer: 'みゃんまーれんぽうきょうわこく',
        capitalAnswer: 'ねーぴーどー'),
    const Country(
        area: '中南米',
        name: 'メキシコ合衆国',
        englishName: 'United Mexican States',
        capitalCity: 'メキシコシティ',
        imageName: 'united_mexican_states',
        language: 'スペイン語',
        currency: 'メキシコ・ペソ',
        nameAnswer: 'めきしこがっしゅうこく',
        capitalAnswer: 'めきしこしてぃ'),
    const Country(
        area: 'アフリカ',
        name: 'モーリシャス共和国',
        englishName: 'Republic of Mauritius',
        capitalCity: 'ポートルイス',
        imageName: 'republic_of_mauritius',
        language: '英語（公用語）、フランス語、クレオール語',
        currency: 'モーリシャス・ルピー',
        nameAnswer: 'もーりしゃすきょうわこく',
        capitalAnswer: 'ぽーとるいす'),
    const Country(
        area: 'アフリカ',
        name: 'モーリタニア・イスラム共和国',
        englishName: 'Islamic Republic of Mauritania',
        capitalCity: 'ヌアクショット',
        imageName: 'islamic_republic_of_mauritania',
        language:
            'アラビア語（公用語、国語）、プラール語、ソニンケ語、ウォロフ語（いずれも国語）。実務言語としてフランス語が広く使われている。',
        currency: 'ウギア',
        nameAnswer: 'もーりたにあ・いすらむきょうわこく',
        capitalAnswer: 'ぬあくしょっと'),
    const Country(
        area: 'アフリカ',
        name: 'モザンビーク共和国',
        englishName: 'Republic of Mozambique',
        capitalCity: 'マプト',
        imageName: 'republic_of_mozambique',
        language: 'ポルトガル語（公用語）、マクア語、シャンガーナ語、チェワ語、セナ語など ',
        currency: 'メティカル',
        nameAnswer: 'もざんびーくきょうわこく',
        capitalAnswer: 'まぷと'),
    const Country(
        area: '欧州',
        name: 'モナコ公国',
        englishName: 'Principality of Monaco',
        capitalCity: 'モナコ',
        imageName: 'principality_of_monaco',
        language: 'フランス語（公用語）',
        currency: 'ユーロ',
        nameAnswer: 'もなここうこく',
        capitalAnswer: 'もなこ'),
    const Country(
        area: 'アジア',
        name: 'モルディブ共和国',
        englishName: 'Republic of Maldives',
        capitalCity: 'マレ',
        imageName: 'republic_of_maldives',
        language: 'ディベヒ語',
        currency: 'ルフィア',
        nameAnswer: 'もるでぃぶきょうわこく',
        capitalAnswer: 'まれ'),
    const Country(
        area: '欧州',
        name: 'モルドバ共和国',
        englishName: 'Republic of Moldova',
        capitalCity: 'キシナウ',
        imageName: 'republic_of_moldova',
        language: 'ルーマニア語。ロシア語も使われている。',
        currency: 'モルドバ・レイ',
        nameAnswer: 'もるどばきょうわこく',
        capitalAnswer: 'きしなう'),
    const Country(
        area: 'アフリカ',
        name: 'モロッコ王国',
        englishName: 'Kingdom of Morocco',
        capitalCity: 'ラバト',
        imageName: 'kingdom_of_morocco',
        language: 'アラビア語（公用語）、ベルベル語（公用語）、フランス語',
        currency: 'モロッコ・ディルハム',
        nameAnswer: 'もろっこおうこく',
        capitalAnswer: 'らばと'),
    const Country(
        area: 'アジア',
        name: 'モンゴル国',
        englishName: 'Mongolia',
        capitalCity: 'ウランバートル',
        imageName: 'mongolia',
        language: 'モンゴル語（国家公用語）、カザフ語',
        currency: 'トグログ',
        nameAnswer: 'もんごるこく',
        capitalAnswer: 'うらんばーとる'),
    const Country(
        area: '欧州',
        name: 'モンテネグロ',
        englishName: 'Montenegro',
        capitalCity: 'ポドゴリツァ',
        imageName: 'montenegro',
        language: 'モンテネグロ語（公用語）、セルビア語など',
        currency: 'ユーロ',
        nameAnswer: 'もんてねぐろ',
        capitalAnswer: 'ぽどごりつぁ'),
    const Country(
        area: '中東',
        name: 'ヨルダン',
        englishName: 'Jordan',
        capitalCity: 'アンマン',
        imageName: 'jordan',
        language: 'アラビア語（英語も通用）',
        currency: 'ヨルダン・ディナール',
        nameAnswer: 'よるだん',
        capitalAnswer: 'あんまん'),
    const Country(
        area: 'アジア',
        name: 'ラオス人民民主共和国',
        englishName: "Lao People's Democratic Republic",
        capitalCity: 'ビエンチャン',
        imageName: 'lao_peoples_democratic_republic',
        language: 'ラオス語',
        currency: 'キープ',
        nameAnswer: 'らおすじんみんみんしゅきょうわこく',
        capitalAnswer: 'びえんちゃん'),
    const Country(
        area: '欧州',
        name: 'ラトビア共和国',
        englishName: 'Republic of Latvia',
        capitalCity: 'リガ',
        imageName: 'republic_of_latvia',
        language: 'ラトビア語',
        currency: 'ユーロ',
        nameAnswer: 'らとびあきょうわこく',
        capitalAnswer: 'りが'),
    const Country(
        area: '欧州',
        name: 'リトアニア共和国',
        englishName: 'Republic of Lithuania',
        capitalCity: 'ビリニュス',
        imageName: 'republic_of_lithuania',
        language: 'リトアニア語',
        currency: 'ユーロ',
        nameAnswer: 'りとあにあきょうわこく',
        capitalAnswer: 'びりにゅす'),
    const Country(
        area: 'アフリカ',
        name: 'リビア国',
        englishName: 'State of Libya',
        capitalCity: 'トリポリ',
        imageName: 'state_of_libya',
        language: 'アラビア語',
        currency: 'リビア・ディナール',
        nameAnswer: 'りびあこく',
        capitalAnswer: 'とりぽり'),
    const Country(
        area: '欧州',
        name: 'リヒテンシュタイン公国',
        englishName: 'Principality of Liechtenstein',
        capitalCity: 'ファドーツ',
        imageName: 'principality_of_liechtenstein',
        language: 'ドイツ語',
        currency: 'スイス・フラン',
        nameAnswer: 'りひてんしゅたいんこうこく',
        capitalAnswer: 'ふぁどーつ'),
    const Country(
        area: 'アフリカ',
        name: 'リベリア共和国',
        englishName: 'Republic of Liberia',
        capitalCity: 'モンロビア',
        imageName: 'republic_of_liberia',
        language: '英語（公用語）、その他各部族語',
        currency: 'リベリア・ドル',
        nameAnswer: 'りべりあきょうわこく',
        capitalAnswer: 'もんろびあ'),
    const Country(
        area: '欧州',
        name: 'ルーマニア',
        englishName: 'Romania',
        capitalCity: 'ブカレスト',
        imageName: 'romania',
        language: 'ルーマニア語（公用語）、ハンガリー語',
        currency: 'レイ',
        nameAnswer: 'るーまにあ',
        capitalAnswer: 'ぶかれすと'),
    const Country(
        area: '欧州',
        name: 'ルクセンブルク大公国',
        englishName: 'Grand Duchy of Luxembourg',
        capitalCity: 'ルクセンブルク',
        imageName: 'grand_duchy_of_luxembourg',
        language: 'ルクセンブルク語、フランス語、ドイツ語',
        currency: 'ユーロ',
        nameAnswer: 'るくせんぶるくたいこうこく',
        capitalAnswer: 'るくせんぶるく'),
    const Country(
        area: 'アフリカ',
        name: 'ルワンダ共和国',
        englishName: 'Republic of Rwanda',
        capitalCity: 'キガリ',
        imageName: 'republic_of_rwanda',
        language: 'ルワンダ語、英語（2009年、公用語に追加され、フランス語に代わって教育言語となった）、フランス語、スワヒリ語',
        currency: 'ルワンダ・フラン',
        nameAnswer: 'るわんだきょうわこく',
        capitalAnswer: 'きがり'),
    const Country(
        area: 'アフリカ',
        name: 'レソト王国',
        englishName: 'Kingdom of Lesotho',
        capitalCity: 'マセル',
        imageName: 'kingdom_of_lesotho',
        language: '英語、ソト語（ともに公用語）',
        currency: 'ロチ',
        nameAnswer: 'れそとおうこく',
        capitalAnswer: 'ませる'),
    const Country(
        area: '中東',
        name: 'レバノン共和国',
        englishName: 'Lebanese Republic',
        capitalCity: 'ベイルート',
        imageName: 'lebanese_republic',
        language: 'アラビア語（フランス語及び英語が通用）',
        currency: 'レバノン・ポンド',
        nameAnswer: 'ればのんきょうわこく',
        capitalAnswer: 'べいるーと'),
    const Country(
        area: '欧州',
        name: 'ロシア連邦',
        englishName: 'Russian Federation',
        capitalCity: 'モスクワ',
        imageName: 'russian_federation',
        language: 'ロシア語',
        currency: 'ルーブル',
        nameAnswer: 'ろしあれんぽう',
        capitalAnswer: 'もすくわ'),
  ];
}
